import { BaseEntity } from './../../shared';

export class ARightPersonMySuffix implements BaseEntity {
    constructor(
        public id?: number,
        public personName?: string,
        public firstName?: string,
        public jobId?: string,
        public lastName?: string,
        public otherName?: string,
        public sex?: string,
        public birthday?: any,
        public pic?: string,
        public icon?: string,
        public mobile?: string,
        public depId?: string,
        public depAddress?: string,
        public depCode?: string,
        public dutyId?: string,
        public dimissionFlag?: string,
        public headerFlag?: string,
        public satrapFlag?: string,
        public leaderFlag?: string,
        public postFlag1?: string,
        public postFlag2?: string,
        public postFlag3?: string,
        public officeTel?: string,
        public fax?: string,
        public mail1?: string,
        public mail2?: string,
        public familyTel?: string,
        public familyAdd?: string,
        public familyCode?: string,
        public personDescribe?: string,
        public idCode?: string,
        public pop3?: string,
        public smtp?: string,
        public mailUsername?: string,
        public mailPassword?: string,
        public mailKeepFlag?: string,
        public personSort?: string,
        public levelNum?: number,
        public personStateId?: string,
        public by01?: string,
        public by02?: string,
        public by03?: string,
        public by04?: string,
        public by05?: string,
        public by06?: string,
        public by07?: string,
        public by08?: string,
        public by09?: string,
        public by10?: string,
        public validType?: string,
        public validBegin?: any,
        public validEnd?: any,
        public insertUserId?: string,
        public insertPersonId?: string,
        public insertTime?: any,
        public upinstantUserId?: string,
        public upinstantPersonId?: string,
        public upinstantTime?: any,
    ) {
    }
}
